version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway-image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      # - TZ=Asia/Yekaterinburg

  server:
    build: server
    image: shareit-server-image
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      # - TZ=Asia/Yekaterinburg
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareIt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:14
    container_name: db
    ports:
      - "6541:5432"
    environment:
      # - TZ=Asia/Yekaterinburg
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root